### ISSUE TITLE
Open Discussion: Invitation for CAMARA from LF Edge China Summit

### ISSUE THREAD

**Issue by ShutingQing** [camaraproject/EdgeCloud#102]
Hi all,

Last time in March, I attended Akraino Spring Summit, which is oraganized by LF Edge, and proposed a round-table topic, 'Panel (with CAMARA): Monetization of Telcos Edge Cloud'.  

And the result is pretty good. LF Edge has known about us. And this time LF Edge is going to hold another event in China. LF Board Tina Tsou invited us yesterday, hoped that I could bring the message to our community. She wishes CAMARA to join and discuss technical or commiercial connections in the field of Edge. 

The event info has not yet been officially released. Right now it's called 'LF Edge Event co-located in Kubecon China'. If anyone have interest, feel free to contact me. 

Last event info attached. 
https://wiki.akraino.org/display/AK/2023+Akraino+Spring+Summit
https://www.linkedin.com/feed/update/urn:li:activity:7060882658821632000/

**Comment by Kevsy** [comment]
Thanks Miranda! I think it will be a good idea to share this event news at the CAMARA steerco, because it is an official LF event.  Do you have a link to the next event please?

**Comment by ShutingQing** [comment]
> hanks Miranda! I think it will be a good idea to share this event news at the CAMARA steerco, because it is an official LF event. Do you have a link to the next event please?

Yeah, you're right. Cuz they're still in planning stage, link is not yet ready. I'll keep our community updated once the event is officially released.

**Comment by ShutingQing** [comment]
@Kevsy The event willl be updated here, once it's released. https://lfnetworking.org/resources/one-summit-regional-days/
