### ISSUE TITLE
Need GPU UUID list for GpuInfo?

### ISSUE THREAD

**Issue by terry-hasegawa** [camaraproject/EdgeCloud#103]
In an application that uses CUDA, UUID is assigned to the application as follows.
To deploy applications to the edge, I think we need a list of UUIDs. Also, GPU usage may be required. These are optional parameters.

A single GPU may have multiple UUIDs.
[`https://docs.nvidia.com/datacenter/tesla/mig-user-guide/#cuda-gi`](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/#cuda-gi)

$ nvidia-smi -L
GPU 0: A100-SXM4-40GB (UUID: GPU-e86cb44c-6756-fd30-cd4a-1e6da3caf9b0)
  MIG 3g.20gb Device 0: (UUID: MIG-c7384736-a75d-5afc-978f-d2f1294409fd)
  MIG 3g.20gb Device 1: (UUID: MIG-a28ad590-3fda-56dd-84fc-0a0b96edc58d)

UUID is assigned to the application
$ CUDA_VISIBLE_DEVICES=MIG-c7384736-a75d-5afc-978f-d2f1294409fd ./BlackScholes &
$ CUDA_VISIBLE_DEVICES=MIG-a28ad590-3fda-56dd-84fc-0a0b96edc58d ./BlackScholes &

I use MIG to split Nvidia GPU to deploy 5G and AI to the edge.
![image](https://github.com/camaraproject/EdgeCloud/assets/126004237/ea7ff69f-8996-4842-bda5-d8148a600a98)

**Comment by Kevsy** [comment]
Hi Terry - please can you clarify which of the CAMARA Edge Cloud APIs this relates to and where they need to change?
