### ISSUE TITLE
Consider a less telco specific term for UEIdentity in simple_edge_discovery.yaml

### ISSUE THREAD

**Issue by RandyLevensalor** [camaraproject/EdgeCloud#121]
The CAMARA commonalities API design guidelines suggests reducing telco specific terminology.  This specifically mentions UE.  See the commonalities section [here](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#25-reduce-telco-specific-terminology-in-api-definitions)

The Simple Edge Discovery API is close to being released, but removing UE from this endpoint could help with onboarding developers that are not steeped in telco terminology.

Perhaps changing `UEIdentity` to `DeviceIdentity` or `UserDeviceIdentity` could be easier to understand.  This would also apply to wireline and Wi-Fi networks, in addition to mobile networks.

**Comment by Kevsy** [comment]
Thanks Randy, good catch - I'll raise that on the commonalities call today to confirm. `UserDeviceIdentity` seems most appropriate  .

**Comment by Kevsy** [comment]
Done in PR #127 (alignining with the same non-telco specific values used in Device Idenitifier and QoD APIs). The term UE also removed from the docuementation.
