### ISSUE TITLE
Folder structure for Gherkin files

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/EdgeCloud#138]
With a reference to step 5 of the Readiness Checklist (https://github.com/camaraproject/Commonalities/blob/main/documentation/API-Readiness-Checklist.md), I would like to agree with you on the folder structure for the Gherking files placement. My idea is to create a folder named “Test” under the already existing folder “code”.
In the Test folder all the APIs can place their Gherkin file (api_name.feature) or they can create a new  subfolder folder named Cucumber if they also provide some code.

**Comment by Kevsy** [comment]
@FabrizioMoggio I like the idea, would the structure be one Test directory per API folder, e.g.

/EdgeCloud/code/API_Definitions/Discovery/Test/ 
/EdgeCloud/code/API_Definitions/Traffic_Influence/Test/

or one Test folder under code? i.e. structure is then 
 
/EdgeCloud/code/API_Definitions/Discovery/foo.yaml
/EdgeCloud/code/API_Definitions/Traffic_Influence/bar.yaml
/EdgeCloud/code/API_Definitions/Test/foo.feature, bar.feature....

WDYT?

**Comment by FabrizioMoggio** [comment]
@Kevsy actually my proposal was based on the old folder structure without the subfolders for each API. Let's consider how it is done in QoD, they decided to go not just with the ".feature" file but with the complete Cucumber solution, that is optional. We should support both the possibilities. For this reason I would suggest to have anyway a "Test" folder with inside or just the ".feature" file or the Cucumber folder structure.

For this reason I suggest to use your option 1:
/EdgeCloud/code/API_Definitions/Discovery/Test/
/EdgeCloud/code/API_Definitions/Traffic_Influence/Test/

QoD/code/cocumber

**Comment by FabrizioMoggio** [comment]
@Kevsy this issue is related, isn't it?

https://github.com/camaraproject/WorkingGroups/issues/302

**Comment by Kevsy** [comment]
Yes - thanks  for adding the reference!

**Comment by FabrizioMoggio** [comment]
Discussion at Commonalities level:

https://github.com/camaraproject/Commonalities/issues/59

**Comment by FabrizioMoggio** [comment]
Closing according to the results of https://github.com/camaraproject/Commonalities/issues/59:

The structure is:

https://github.com/camaraproject/Template_Lead_Repository
