### ISSUE TITLE
Folder structure for release Branches

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/EdgeCloud#140]
the main branch has a new folder structure, with subfolders for each APIs. The same structure is not adopted in the release branches. how can we fix this?

**Comment by FabrizioMoggio** [comment]
A proposal based on https://github.com/camaraproject/Commonalities/issues/66 :

**release-0.8.1**: it is ok: it still has the old folder structure without subfolder for each API in the Family. This is correct because the branch is a snapshot done when the Edge Cloud Family had that folder structure.

**release-0.9.0, 1.0.0, 2.0.0**: currently they are branches used for development while according to https://github.com/camaraproject/Commonalities/issues/66 these branches should be used as snapshot from Main when we decide to deliver a stable version. 

I suggest to:

-  rename these branches with the prefix "dev-", for example: "dev-release-0.9.0". It is up to who is using that branches to restructure them according to the new folder structure.
-  create new PRs to push the relevant developed code into Main

**Comment by Kevsy** [comment]
@FabrizioMoggio  Yes, as agreed in the call 12-12-23 I will:

- delete release-1.0.0 and release-2.0.0
- rename release-0.9.0 to dev-release-0.9.0

...however, I don't have permissions to do this as they are 'protected branches' (hence require admin permissions). @MarkusKuemmerle please can you advise..?

**Comment by FabrizioMoggio** [comment]
@MarkusKuemmerle, @gunjald I think that also release-0.9.0 can be deleted at this point in time

**Comment by hdamker** [comment]
@Kevsy @FabrizioMoggio: On request of @Kevsy I have:
* deleted release-1.0.0 and release-2.0.0
* renamed release-0.9.0 to obsolete-0.9.0 (that will allow code owners to rename/delete it as needed)

Please be aware of [updating-a-local-clone-after-a-branch-name-changes](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes) in case you have local clones.
