### ISSUE TITLE
Documentation enhancement for edge discovery API

### ISSUE THREAD

**Issue by gunjald** [camaraproject/EdgeCloud#148]
For simple_edge_discovery.yaml, the "purpose" says " Network operators may host multiple Multi-access Edge Computing (MEC, or 'Edge') platforms in a given territory. Connecting your application to a server on the closest MEC platform means packets travel the shortest distance between endpoints, typically resulting in the lowest round-trip latency"

The part of the above statement "Connecting your application to a server on the closest MEC platform" seems to valid when the "application" refers to the software that is running on user terminal or user device. If that is correct then I think if the word "application" is rephrased as "Device Application" or "User Client" or any other better term to indicate it is intended to be on an end user device and not any cloud or internet application to avoid any confusion..

**Comment by Kevsy** [comment]
Good catch - thanks @gunjald . I've updated the purpose to say

`connect the application client on the user device`

PR #146 updated , please can you merge the PR if no further issue?
