### ISSUE TITLE
Simple Edge Discovery ressources names are not descriptive

### ISSUE THREAD

**Issue by leochely** [camaraproject/EdgeCloud#150]
I have noticed that within the resources, some of the resource names do not adhere to the naming conventions defined in the [API Design Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#42-inputoutput-resource-definition). Specifically, I'd like to address the resource names `Ern` and `Provider`.

To maintain code consistency and improve clarity, I propose that we consider renaming these resources to `edgeResourceName` and `provider`. They should be made more descriptive and updated to follow the lower camel case convention.

I believe that making these changes will enhance the overall maintainability and readability of the API.

**Comment by Kevsy** [comment]
Thanks @leochely  - 

For `Ern`, I agree the name is not descriptive and I will change it to `edgeResourceName`

Do you have a suggestion for `Provider`? I think 'cloudProvider` as the goal is to let the developer known which cloud provider they need to interact with following this API response.

**Comment by Kevsy** [comment]
...or `edgeCloudProvider` to better match the API family name :)

**Comment by leochely** [comment]
Yes I think the `edgeCloudProvider` name would be the best
