### ISSUE TITLE
Simple Edge discovery API method parameters do not use lower camel case as in the rest of CAMARA APIs

### ISSUE THREAD

**Issue by sergiofranciscoortiz** [camaraproject/EdgeCloud#158]
Similarly to the issue #151, we have noticed that apart from resource names, method attributes/parameters in Simple Edge Discovery API do not follow lower camel case naming.

Although it is apparently not strictly indicated in [API Design Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#34-path-parameters-use), it is defined to use camel case convention in several items and somehow hints to use it generally.

Furthermore it seems to be the widely use in other published CAMARA APIs as for example in [BlockchainPublicAddress API](https://github.com/camaraproject/BlockchainPublicAddress/blob/main/code/API_definitions/blockchain_public_address.yaml), where the use phoneNumber as parameter for the method.

The suggestion is to adapt all paramaters to lower camel case notation, that would include:

| Current Parameter Name  | Suggested lower camel case name |
| ------------- | ------------- |
| IP-Address  | ipAddress |
| Network-Access-Identifier  | networkAccessIdentifier |
| Phone-Number  | phoneNumber |

**Comment by sergiofranciscoortiz** [comment]
OK thanks, we can wait for the outcome of the discussion in commonalities.

**Comment by Kevsy** [comment]
Updated the [Commonalities issue](https://github.com/camaraproject/Commonalities/issues/105#issuecomment-1882832450) as the Simple Edge Discovery API provides Device Identifiers as Headers (for which Uppercase-hyphen is the de facto standard).

**Comment by Kevsy** [comment]
Now raised as [PR 120 in Commonalities](https://github.com/camaraproject/Commonalities/pull/120) 

If approved, then I will update the Simple Edge Discovery API to import those definitions.

**Comment by Kevsy** [comment]
Outcome: [agreed in Commonalities  ](https://github.com/camaraproject/Commonalities/pull/120#issuecomment-2023131188)that Upper-kebab-case is appropriate for HTTP headers
