### ISSUE TITLE
TI and MVP API - Harmonization of common entities

### ISSUE THREAD

**Issue by javierlozallu** [camaraproject/EdgeCloud#164]
The following entities are defined in the current [MVP API v0.2.0](https://github.com/camaraproject/EdgeCloud/pull/154):

- `appId`
- `appInstanceId`

We find these entities in common with the following TI API entities:
- `applicationId`
- `instanceId`

Our proposal is to keep `appId `and `appInstanceId` as per CAMARA Guidelines for good practices; short URIs use is recommended for relevant entities. We defined the method /app (appId to identified) and /appInstance (appInstanceId to identified) to keep it readable and simple according to the guidelines. As TI in [Traffic Influence Release 0.9.1](https://github.com/camaraproject/EdgeCloud/pull/110)  inherits these entities from [EdgeCloudApi_v0.0.5 - Capgemini](https://github.com/camaraproject/EdgeCloud/blob/main/code/API_definitions/Resource%20Management/EdgeCloudApi_v0.0.5.yaml) (which will be included in the MVP API as discussed in the last [CAMARA Meeting](https://wiki.camaraproject.org/display/CAM/2023-12-12%3A+SP-EDC+Minutes)), the appId and appInstanceId entities should be inherited from MVP API as well.

Anyhow, `applicationId` could be adopted in MVP API and is open to discussion, `instanceId` should be changed to `appInstanceId` or `applicationInstanceId`.

**Comment by FabrizioMoggio** [comment]
It is fine to me. I will update the TI API accordingly.

**Comment by FabrizioMoggio** [comment]
https://github.com/camaraproject/EdgeCloud/pull/167

**Comment by sergiofranciscoortiz** [comment]
Issue adressed in https://github.com/camaraproject/EdgeCloud/pull/167. Closing ticket.
