### ISSUE TITLE
Propose to convert several issues to Discussions

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/EdgeCloud#169]
Now that we have a new Discussion tab, I propose to move some of the issues there. The 'Intent Analysis' items were all intended to be discussions for example.

@crissancas @sergiofranciscoortiz @ThomasEdgeXR @gunjald any objection? I can do the moving.

**Comment by ThomasEdgeXR** [comment]
Full support, makes sense! Thanks @Kevsy!
