### ISSUE TITLE
Rename traffic Influence in .yaml file line 7

### ISSUE THREAD

**Issue by MarkCornall** [camaraproject/EdgeCloud#243]
**Problem description**
Traffic influence is named as "OPAG-CAMARA Traffic Influence API" in the .yaml

**Expected action**
Please can it be renamed as "Traffic Influence API"

**Additional context**
The inclusion of OPAG-CAMARA is probably confusing

**Comment by FabrizioMoggio** [comment]
Merged rel 0.9.5
