### ISSUE TITLE
TI API: 3Legs problem for GET methods

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/EdgeCloud#250]
**Problem description**
GET methods are currently adopting OpenId. This is a mistake because they are invoked when the user is not online to give consent and anyway they provide back to the API Consumer information that are already previously managed via OpenId in the POST methods.

The same applies for the DELETE method

**Expected behavior**
Because the Get methods provide back information to the API Consumer on resources created with POST using Consent Management we should secure those Get methods with client/credential. 

The same applies for the DELETE method.

**Comment by FabrizioMoggio** [comment]
Asked to Commonalities: https://github.com/camaraproject/Commonalities/discussions/245

**Comment by javierlozallu** [comment]
CAMARA document where some implementation guidelines for 3 Legs are defined: [CAMARA-API-access-and-user-consent.md](https://github.com/camaraproject/IdentityAndConsentManagement/blob/release-0.1.0/documentation/CAMARA-API-access-and-user-consent.md#authorization-code-flow-frontend-flowl). 
`Every time personal user data is processed by an API and the user can exercise their rights either via opt-in and/or opt-out, 3-legged access tokens must be used.`

**Comment by FabrizioMoggio** [comment]
According to: https://github.com/camaraproject/IdentityAndConsentManagement/discussions/184#discussioncomment-10199372

Conclusion: there are techniques to keep the token alive and to access the APIs not interacting with the user that, at this point in time, as already provided the consent. For these reason, these endpoints can still be with 3legs.
