### ISSUE TITLE
EdgeXR proposed Application Instance Management APIs

### ISSUE THREAD

**Issue by gainsley** [camaraproject/EdgeCloud#30]
EdgeXR should propose their APIs for Application Instance Management APIs (i.e. lifecycle management). These APIs take a previously created definition of an Application, plus a target cloudlet (edge site), and deploy an instance of that application to the cloudlet. Once the instance is deployed, it is discoverable via the Application Edge Discover APIs (#28).

**Comment by Kevsy** [comment]
These are now contributed
