### ISSUE TITLE
Traffic Influence API

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/EdgeCloud#35]
As agreed in the API Backlog WG, the Traffic Influence API could be moved in the Edge Cloud WG. The functionality (traffic routing between CN and the Application) can indeed be requested by the user as a requirement in the application upload, although a specific API can be directly exposed for simpler use cases. For this reason, it would be more efficient to discuss the functionality in the Edge Cloud WG and, consequently, to implement the API in the same WG avoiding the overhead of creating a specific WG.

**Comment by FabrizioMoggio** [comment]
Here is the details for the proposed API
[CAMARA Traffic Influence v1.4.pptx](https://github.com/camaraproject/EdgeCloud/files/9653438/CAMARA.Traffic.Influence.v1.4.pptx)

**Comment by Kevsy** [comment]
Agreed on call 11th October that YAML can be contributed for sub-project review

**Comment by FabrizioMoggio** [comment]
the TI API is part of the Edge Cloud Family. We can close the issue.
