### ISSUE TITLE
[MEC Discovery API] Unused definitions in the specification

### ISSUE THREAD

**Issue by carloslozano** [camaraproject/EdgeCloud#37]
The following shared responses are defined in the "simple_edge_discovery.yaml" OAS3 specification:

- [OK](https://github.com/camaraproject/EdgeCloud/blob/ee44585bb1db384808cbe7b955613993031d0b58/code/API_definitions/simple_edge_discovery.yaml#L320)
- [Created](https://github.com/camaraproject/EdgeCloud/blob/ee44585bb1db384808cbe7b955613993031d0b58/code/API_definitions/simple_edge_discovery.yaml#L326)
- [NoContent](https://github.com/camaraproject/EdgeCloud/blob/ee44585bb1db384808cbe7b955613993031d0b58/code/API_definitions/simple_edge_discovery.yaml#L332)
- [BadRequest](https://github.com/camaraproject/EdgeCloud/blob/ee44585bb1db384808cbe7b955613993031d0b58/code/API_definitions/simple_edge_discovery.yaml#L334)
- [NotFound](https://github.com/camaraproject/EdgeCloud/blob/ee44585bb1db384808cbe7b955613993031d0b58/code/API_definitions/simple_edge_discovery.yaml#L340)

These are not being used/referenced anywhere within the specification.

- [GET /](https://github.com/camaraproject/EdgeCloud/blob/ee44585bb1db384808cbe7b955613993031d0b58/code/API_definitions/simple_edge_discovery.yaml#L34) - defines unshared/inline schema 200 response
- [GET /mecplatforms](https://github.com/camaraproject/EdgeCloud/blob/ee44585bb1db384808cbe7b955613993031d0b58/code/API_definitions/simple_edge_discovery.yaml#L72) - defines unshared/inline schema 200 response

Please consider _preferably_ using shared response schema or removing unused shared response components.

**Comment by Kevsy** [comment]
Thanks for the catch! Will do.
