### ISSUE TITLE
Update commonalities glossary with EdgeCloud-subproject relevant terms

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/EdgeCloud#54]
https://github.com/camaraproject/WorkingGroups/pull/120

**Comment by rartych** [comment]
In order to integrate the common glossary in Commonalities it is needed to provide the first version of subproject relevant terms by **15th of March**.

It looks that this issue is related to https://github.com/camaraproject/EdgeCloud/issues/40.

**Comment by Kevsy** [comment]
@rartych this will be delayed for EdgeCloud as we have 3 sets of terminology to harmonise...it's underway though as part of the wider API harmonisation effort.

**Comment by rartych** [comment]
I agree.  The first set of terms is aggregated here: https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Glossary.md 

In the harmonisation effort it is important to use "the developer-friendly terms" - the Glossary could be the hint.
