### ISSUE TITLE
TI API: LBO with PDU session already active

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/EdgeCloud#56]
To discuss if the current TI API v0.8.1 is already compatible with a Use Case where it is invoked for already active sessions.

**Comment by FabrizioMoggio** [comment]
The focal point is to have clear the coordinates for the active session if we are considering a single user. So we need to know the UE IP and the EAS IP.

In the current version of the TI API, the EAS IP is retrieved by the OP starting from the applicationId input parameter. The current scope of the TI API is indeed related to Application onboarded with the CAMARA API and deployed in the Telco Infrastructure so they all have an applicationId and the OP is aware if the IP addresses of each instance.

For the UE IP the TI API has the userId parameter. It can be: IPAddress, MSISDN, IMEI, MDN, GPSI. From MSISDN and GIPSI the OP is able to identify the UE IP to be used in the UPF (also discriminating between possible Private or Public IP because of CGNAT). What about MDN and IMEI, anyone knows?

**Comment by babunkj** [comment]
There was this question whether the Application needs to provide the IP Address in case of a traffic influence for an active session. The IP Address could also be a NAT'd one. There are ways in which the OP can fetch the IP Addr using the UE Id like GPSI/SUPI, for example using Event Monitoring service. 
Another service has also been introduced in R17 called Nnef_UEId service, which is however for retrieving the external UE Id (GPSI) using an IP Address. In this case, the specs notes that the NATed (Network and Port Address Translation) IP address is not supported in the release. 
We can make appropriate recommendations based on the above.

**Comment by FabrizioMoggio** [comment]
one note: the 3GPP TI API gets, as input to identify the UE, the GPSI. So we should understand if the list of possible options we have to identify the UE (IPAddress, MSISDN, IMEI, MDN, GPSI) let the OP to retrieve the GPSI.

**Comment by FabrizioMoggio** [comment]
I discussed this topic in OPAG and the suggestion is to avoid to use IMEI and MDN. IMEI is a sensitive information and it does not allow to identify the network that that device is connected to. It is indeed related to the device rather than actually providing an identification of the network used by the device. This prevent to use it in roaming scenarios and federation. MDN is considered obsolete when working on 4G and 5G networks. 

I would also suggest to update the userid parameter to match the CAMARA guidelines on EU Identification: https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/UE-Identification.md

The guidelines suggest to use GPSI, IP or MAC.

A general alignment with the other APIs in CAMARA on UE Identification is needed.

**Comment by babunkj** [comment]
Yes, I agree. The API can be used for the purpose of influencing active sessions too, by giving the appropriate parameters that will help OP identify the specific traffic in a PDU Session to be influenced. If UE IP Addr is provided, the PDU session can be identified directly with it. If GPSI (MSISDN or Externa identifier) is given, additional info like the App Id can help OP identify the correct session among the multiple that may have been established from the UE.

**Comment by FabrizioMoggio** [comment]
To align the TI API with the Glossary (https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Glossary.md) it is better to rename UE as Device. Also MSISDN should be renamed as PhoneNumber. For this reason it is proposed to adopt the implementation done in QoD for the parameter Device.

**Comment by FabrizioMoggio** [comment]
Closed with the UE parameter modified as Device containing arguments that represent GSPI.

PR TI V0.9.0: https://github.com/camaraproject/EdgeCloud/pull/105
