### ISSUE TITLE
New Branch for Traffic Influence next release

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/EdgeCloud#62]
@crissancas: As discussed in Commonalities (issue 118: https://github.com/camaraproject/WorkingGroups/issues/118) we can manage branches according to our needs. What is important (as documented in "Camara subproject release guidelines": https://github.com/camaraproject/WorkingGroups/pull/123/files#diff-1781e49a2c0b247e843170f708bced97c9d790feeb91297a7a92ceef995f22fd) is to use the Release Tag feature from Github, in the Main Repo, when all the branches are merged, to mark a release for the API Family. It is also important to create a CHANGELOG.md file for the release.

To move forward I suggest two possible options:

To move forward with a new release for the entire API Family, we could create a new branch named release-2.0.0 (as defined in "Camara subproject release guidelines"). 

If we want to proceed with just a new release for the TI API,  we could create a new branch just for it with the name: TI_API_V2.

Anyway, before merging the V2 branch we should create a branch for v1.0.0 to complete the current release with some further suggestion from Commonalities (issue 50: https://github.com/camaraproject/EdgeCloud/issues/50).

I also add @Kevsy in the request.

**Comment by FabrizioMoggio** [comment]
I did some further reasoning, to manage both v1 and v2 as Release Braches according to "Camara subproject release guidelines". I suggest to create two new Release Branches named as:

- release-1.0.0
- release-2.0.0

The first one must be used to update v0.8 according to the inputs from Commonalities. This branch must be use only when the guidelines are consolidated. 

The second one is to start immediately to work on the next release adding new features, e.g. User Mobility for the Traffic Influence API.

**Comment by FabrizioMoggio** [comment]
Just one more comment, I also opened an issue for the Release Tag (Issue 63) (https://github.com/camaraproject/EdgeCloud/issues/63).

So the flow should be:
1) Create a Release Tag on Main (this is to freeze the release for MWC)
2) Open the two branches for v1 and v2

**Comment by Kevsy** [comment]
release-1.0.0 and release-2.0.0 branches created
