### ISSUE TITLE
Edge Model: how will APIs be offered?

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/EdgeCloud#83]
received from @PrashantGDT 

"How will these APIs will be offered to customers. Through one common single platform or there will multiple platform owned by different operators?"

**Comment by gunjald** [comment]
In my understanding any operator who want to provide these services as exposed by the APIs should be able to independently offer them to their customers. In case of GSMA Operator Platform based implementation, the APIs can also be federated between the two operators and in that case one operator can front end the APIs from its customers and forward the APIs to other operators responsible for that request provided the other operator via their operator platform also provide support for these APIs.

**Comment by Kevsy** [comment]
How they are offered is out of scope of CAMARA, but as @gunjald says this is being discussed in other groups. But basically it will be flexible: operators can expose themselves, via partners, via a federation etc,.
