### ISSUE TITLE
Edge model: alternative to harmonising the APIs

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/EdgeCloud#86]
From @PrashantGDT 

As you mentioned that we might need to work on an abstract version of an API,  that seems to be a good approach but that will requires some discussion and consensus among all.
May be another approach is like a free approach where everybody is free to select his version of implementation and other acts an simple roaming partner 
This eliminates the conflict and necessity of reaching the consensus for each API.

**Comment by Kevsy** [comment]
> This eliminates the conflict and necessity of reaching the consensus for each API.

That's true, but this would require a point-to-point integration and API transformation between operators with different APIs. Since there are not many operators deploying this kind of API we have a chance to reduce that complexity through a commonly-supported definition.

**Comment by PrashantGDT** [comment]
Hi Kevin,
                             Completely agree with the thought that we can make use of opportunity to reduce that complexity through a commonly-supported definition.
As general grouping of APIs is as below, We can start with Discovery Management APIs, Registration and MACD of Applications APIs etc.


Current APIs as proposed for harmonisation

EdgeXR
1. CreatAPP/DeleteApp/ShowApp/UpdateApp  ( This is about Application (Meta data), instance of which will be deployed on EdgeCloud locations)
2. MatchEngineAPIs  (APIs for application clients on devices to interact with Edge Cloud application services like Best EdgeCloud,bestEdgeApplicationInstances, Event notifications etc.)
3. Session API (Registers the client with the closest Distributed Matching Engine and validates the legitimacy of the mobile subscriber)

Capgemini)
1. Application provider resource management  (Resource Reservation Management)
2. Application Artifact management
3. Application On boarding Management
4. Application Instance Lifecycle management
5  Edge Cloud Zone Management
6. Application provider Identity Management

5GFF
1. Discovery API
2. Register and manage the service endpoints
3. Create and manage Service profiles
4. Simple MEC Discovery API

Thanks

BR
Prashant Goswami
